name: mf6rtm continuous integration - macOS

on:
  schedule:
    - cron: '0 8 * * *' # run at 8 AM UTC (12 am PST)
  push:
    branches:
      - develop
  pull_request:
    branches: [main, develop, feature/**]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ['310', '311', '312', '313']
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.9.3
      with:
        log-level: vvv
        pixi-version: v0.41.4
        cache: true
        environments: py${{ matrix.python-version }}

    - name: Install environment
      run: pixi install -e py${{ matrix.python-version }}

    - name: Run tests
      run: pixi run -e py${{ matrix.python-version }} test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
